#!/bin/bash
./moving_cube1.sh
./moving_cube2.sh
./moving_cube3.sh
./moving_cube4.sh
./moving_cube5.sh
./moving_pyramid1.sh
./moving_pyramid2.sh
./moving_pyramid3.sh
./moving_pyramid4.sh
./moving_pyramid5.sh
