all: main 
main: conv.c 
	gcc -g -Wall -pedantic -fno-stack-protector -lm conv.c -o main
	#./main GrumpyCat.ppm NiceDog.ppm add.ppm add
	#./main GrumpyCat.ppm NiceDog.ppm mul.ppm mul
	#./main GrumpyCat.ppm NiceDog.ppm avga.ppm avga
	#./main GrumpyCat.ppm NiceDog.ppm avgg.ppm avgg
	#./main GrumpyCat.ppm NiceDog.ppm sin1.ppm sin1
	#./main GrumpyCat.ppm NiceDog.ppm sin2.ppm sin2
	#./main GrumpyCat.ppm NiceDog.ppm sin3.ppm sin3
	#./main GrumpyCat.ppm NiceDog.ppm sinh1.ppm sinh1
	#./main GrumpyCat.ppm NiceDog.ppm sinh2.ppm sinh2
	#./main GrumpyCat.ppm NiceDog.ppm sinh3.ppm sinh3
	#./main GrumpyCat.ppm NiceDog.ppm quad1.ppm quad1
	#./main GrumpyCat.ppm NiceDog.ppm quad2.ppm quad2
	#./main GrumpyCat.ppm NiceDog.ppm quad3.ppm quad3
	#./main GrumpyCat.ppm NiceDog.ppm quadsum.ppm quadsum
	#./main GrumpyCat.ppm NiceDog.ppm logarithm1.ppm logarithm1
	#./main GrumpyCat.ppm NiceDog.ppm logarithm2.ppm logarithm2
	#./main GrumpyCat.ppm NiceDog.ppm logarithm3.ppm logarithm3
	#./main GrumpyCat.ppm NiceDog.ppm exponential1.ppm exponential1
	#./main GrumpyCat.ppm NiceDog.ppm exponential2.ppm exponential2
	#./main GrumpyCat.ppm NiceDog.ppm exponential3.ppm exponential3
	#./main GrumpyCat.ppm NiceDog.ppm exponential4.ppm exponential4
	#./main GrumpyCat.ppm NiceDog.ppm runsum1.ppm runsum1
	#./main GrumpyCat.ppm NiceDog.ppm runsum2.ppm runsum2
	#./main GrumpyCat.ppm NiceDog.ppm runsum3.ppm runsum3
	#./main GrumpyCat.ppm NiceDog.ppm modboth1.ppm modboth1 
	#./main GrumpyCat.ppm NiceDog.ppm modboth2.ppm modboth2 
	#./main GrumpyCat.ppm NiceDog.ppm andboth.ppm andboth 
	#./main GrumpyCat.ppm NiceDog.ppm orboth.ppm orboth 
	#./main GrumpyCat.ppm NiceDog.ppm xorboth.ppm xorboth 
	#./main GrumpyCat.ppm NiceDog.ppm conditional1.ppm conditional1
	#./main GrumpyCat.ppm NiceDog.ppm conditional2.ppm conditional2
	#./main GrumpyCat.ppm NiceDog.ppm digitsum1.ppm digitsum1
	#./main GrumpyCat.ppm NiceDog.ppm digitsum2.ppm digitsum2
	#./main GrumpyCat.ppm NiceDog.ppm fibs1.ppm fibs1
	#./main GrumpyCat.ppm NiceDog.ppm fibs2.ppm fibs2
	#./main GrumpyCat.ppm NiceDog.ppm xform1.ppm xform1 
	#./main GrumpyCat.ppm NiceDog.ppm nchoosek1.ppm nchoosek1
	viewnior out.ppm
	#rm main
